### ISSUE TITLE
Feature Request:  Accept Glob/File[]

### ISSUE THREAD

**Issue by Kaffiend** [fritx/cross-unzip#4]
Would be fantastic to have it accept a glob pattern or array of strings for the archive.

**Comment by Kaffiend** [comment]
disregard, can be passed with command line arguments

**Comment by fritx** [comment]
@Kaffiend oh didn't test it.
You mean we already have this feature, 'cause the glob is passed as cli args to [win-7zip](https://github.com/fritx/win-7zip)?

**Comment by Kaffiend** [comment]
Correct
