### ISSUE TITLE
win-7zip error on production, works on test

### ISSUE THREAD

**Issue by haroldallen** [fritx/cross-unzip#8]
![image](https://user-images.githubusercontent.com/67546646/207411619-9cdb8825-e1e6-4daa-8dca-b6d904dc0329.png)
This error appears when my program tries to unzip a zip file to a folder once my Electron app has been built, but works when I test it (without building).
This may be some permissions issue, if it is, sorry, I can't tell.

**Comment by fritx** [comment]
@foxlldev hi, I'm not sure either whether it is a permission issue came from the packing step of Electron,
as the tests including Windows [are passing](https://github.com/fritx/cross-unzip/actions).

It is a common error `ENOENT` thrown by `spawn` in Windows, which I've ever came across many times as well.
Replacing `spawn` with `cross-spawn` was one of my choice in the past.
https://stackoverflow.com/questions/37459717/error-spawn-enoent-on-windows

I'm wondering which one should I try this time:
1. passing `shell: true` in Windows
2. switching to `cross-spawn`
3. find out the permission issue if it is

**Comment by haroldallen** [comment]
Sorry, I should have given further details:
My code is:
```js
function unzipToFolder(targetPath, destPath) {
  if (!fs.existsSync(destPath)) {
    fs.mkdirSync(destPath);
  }
  
  unzip(targetPath, destPath, err => {
    if (err) {
      console.log('Error while unzipping '+targetPath+' to '+destPath, err);
    } else { console.log('Successfully unzipped '+targetPath+' to '+destPath); }
  })
}
```
Anything I've done wrong?
I'm not using .spawn, should I be?

**Comment by fritx** [comment]
> I'm not using .spawn, should I be?

@foxlldev sorry, I was to mean the `spawn` in cross-unzip source code 😂 
https://github.com/fritx/cross-unzip/blob/dev/index.js#L52

> Sorry, I should have given further details:
My code is:

I'll try to do this in a Windows machine with Electron later 👀

**Comment by fritx** [comment]
@foxlldev after some search, I found some relative issues like
https://github.com/electron/asar/issues/35
https://github.com/bencevans/screenshot-desktop/issues/135

Maybe you can try the below:

```js
// package.json
 "win": {
      "extraResources": [
        "node_modules/win-7zip/7zip-lite/7z.exe"
      ]
  }
```

**Comment by haroldallen** [comment]
That sounds great, I will try your solution as soon as I can.

**Comment by haroldallen** [comment]
Unfortunately this fix does not seem to be working.

I have analysed the error myself (not to doubt your analysis, but I wondered if I could decode it):
- it seems to be that it cannot find the win-7zip module in the app's app.asar in the resources folder
- the fix you provided adds the 7zip package to a node_modules folder in the resources folder but not in the app.asar which is where it is being requested

By the way, please note I am building the app on my Ubuntu server as due to random issues I cannot build it on my Windows machine.

**Comment by haroldallen** [comment]
Nevermind, it does seem to include win-7zip and its correct included files in the app.asar.
So maybe try switching from switch to cross-switch in your source code.

**Comment by haroldallen** [comment]
I have tried this cross-spawn modification myself and yet it still does not work. I shall be looking into this futher later.
